# Generated by Django 4.2 on 2023-05-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. kernel_info', max_length=100, unique=True)),
                ('test_command', models.CharField(help_text='e.g. uname -r', max_length=300)),
                ('expect_result', models.TextField(blank=True, help_text='e.g. 5.3.0-24-generic', max_length=300)),
                ('display_ok_type', models.CharField(choices=[('TYPE1', 'Show OK if there is any result'), ('TYPE2', 'Show OK if result is the same as expect_result field'), ('TYPE3', 'Show just result without OK'), ('TYPE4', 'Do not show OK')], default='TYPE1', max_length=100, verbose_name='How to display result to OK')),
                ('display_fail_type', models.CharField(choices=[('TYPE1', 'Show Fail if there is no result'), ('TYPE2', 'Show Fail if result is not the same as expect_result field'), ('TYPE3', 'Do not show Fail')], default='TYPE1', max_length=100, verbose_name='How to display result to fail')),
                ('resume_command', models.CharField(blank=True, help_text='e.g. uname -r. if test stage failed, this will be shown to resume', max_length=300)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
