# Generated by Django 4.2 on 2023-05-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=12, verbose_name='IP address')),
                ('port', models.CharField(max_length=4, verbose_name='Port')),
                ('proxy_type', models.CharField(choices=[('None', 'None'), ('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('SOCKS4', 'SOCKS4'), ('SOCKS5', 'SOCKS5')], default='HTTP', max_length=10, verbose_name='Proxy types')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name has to be unique', max_length=100, unique=True, verbose_name='Resource name')),
                ('addr', models.CharField(help_text='e.g. 0.0.0.0', max_length=12, verbose_name='IP address')),
                ('port', models.CharField(max_length=4, verbose_name='Port')),
                ('user_id', models.CharField(help_text='user id to access', max_length=100, verbose_name='User ID')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('connect_addr_list', models.CharField(blank=True, help_text='e.g. 0.0.0.0/1.1.1.1/2.2.2.2', max_length=300, verbose_name='IP list of require connection')),
                ('ci_agent_path', models.CharField(blank=True, help_text='if you use this resource with CI agent such as bamboo', max_length=300, verbose_name='Path of CI agent')),
                ('disabled', models.BooleanField(help_text='if the resource is not necessary', verbose_name='Disabled')),
                ('proxy_server', models.ForeignKey(blank=True, default='None', help_text='select proxy server if necessary', null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.proxyserver')),
                ('type', models.ForeignKey(help_text='select a resource type', on_delete=django.db.models.deletion.PROTECT, to='resources.resourcetype')),
            ],
        ),
    ]
