# Generated by Django 4.2 on 2023-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resources_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='addr',
            field=models.CharField(max_length=15, verbose_name='IP address'),
        ),
    ]
